//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace DarkBot.Net.Presentation.Resources;

using System.Globalization;
using System.Resources;

/// <summary>
/// Локализованные строки интерфейса (ru-RU, основная сборка).
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public static class UiStrings
{
    private static readonly ResourceManager ResourceManager =
        new("DarkBot.Net.Presentation.Resources.UiStrings", typeof(UiStrings).Assembly);

    private static CultureInfo? _resourceCulture;

    /// <summary>
    /// Переопределяет текущую культуру для чтения ресурсов.
    /// </summary>
    public static CultureInfo? Culture
    {
        get => _resourceCulture;
        set => _resourceCulture = value;
    }

    public static string App_Title => GetString(nameof(App_Title));
    public static string App_TitleRunning => GetString(nameof(App_TitleRunning));
    public static string App_TitlePaused => GetString(nameof(App_TitlePaused));
    public static string ConfigWindow_Title => GetString(nameof(ConfigWindow_Title));
    public static string ConfigWindow_Header => GetString(nameof(ConfigWindow_Header));
    public static string ConfigWindow_Subtitle => GetString(nameof(ConfigWindow_Subtitle));
    public static string ConfigWindow_Badge => GetString(nameof(ConfigWindow_Badge));
    public static string ConfigMain_PageTitle => GetString(nameof(ConfigMain_PageTitle));
    public static string ConfigMain_Module => GetString(nameof(ConfigMain_Module));
    public static string ConfigMain_ModuleKillCollect => GetString(nameof(ConfigMain_ModuleKillCollect));
    public static string ConfigMain_WorkingMap => GetString(nameof(ConfigMain_WorkingMap));
    public static string ConfigMain_Security => GetString(nameof(ConfigMain_Security));
    public static string ConfigMain_SaveHealthInRange => GetString(nameof(ConfigMain_SaveHealthInRange));
    public static string ConfigCollect_PageTitle => GetString(nameof(ConfigCollect_PageTitle));
    public static string ConfigPlaceholder_PageTitle => GetString(nameof(ConfigPlaceholder_PageTitle));
    public static string Login_UnityClientBadge => GetString(nameof(Login_UnityClientBadge));
    public static string Login_Title => GetString(nameof(Login_Title));
    public static string Login_Description => GetString(nameof(Login_Description));
    public static string Login_UsernamePlaceholder => GetString(nameof(Login_UsernamePlaceholder));
    public static string Login_PasswordPlaceholder => GetString(nameof(Login_PasswordPlaceholder));
    public static string Login_RememberMe => GetString(nameof(Login_RememberMe));
    public static string Login_StatusTitle => GetString(nameof(Login_StatusTitle));
    public static string Login_Cancel => GetString(nameof(Login_Cancel));
    public static string Login_Submit => GetString(nameof(Login_Submit));
    public static string Login_DesignMode => GetString(nameof(Login_DesignMode));
    public static string Login_LaunchingGame => GetString(nameof(Login_LaunchingGame));
    public static string Login_CredentialsRequired => GetString(nameof(Login_CredentialsRequired));
    public static string Main_ConfigButton => GetString(nameof(Main_ConfigButton));
    public static string Main_LoginButton => GetString(nameof(Main_LoginButton));
    public static string Main_RestartClientTooltip => GetString(nameof(Main_RestartClientTooltip));
    public static string Main_PhaseLabel => GetString(nameof(Main_PhaseLabel));
    public static string Main_StartButton => GetString(nameof(Main_StartButton));
    public static string Main_PauseButton => GetString(nameof(Main_PauseButton));
    public static string Main_Ready => GetString(nameof(Main_Ready));
    public static string Main_ReadyDesignMode => GetString(nameof(Main_ReadyDesignMode));
    public static string Status_GameNotLaunched => GetString(nameof(Status_GameNotLaunched));
    public static string Status_OnMapActive => GetString(nameof(Status_OnMapActive));
    public static string Status_Connecting => GetString(nameof(Status_Connecting));
    public static string Status_Authenticating => GetString(nameof(Status_Authenticating));
    public static string Status_InHangar => GetString(nameof(Status_InHangar));
    public static string Status_EnteringMap => GetString(nameof(Status_EnteringMap));
    public static string Status_Launching => GetString(nameof(Status_Launching));
    public static string Status_WaitingLoad => GetString(nameof(Status_WaitingLoad));
    public static string Status_WaitingConnection => GetString(nameof(Status_WaitingConnection));
    public static string Status_LaunchFailed => GetString(nameof(Status_LaunchFailed));
    public static string Status_LaunchFailedWithReason => GetString(nameof(Status_LaunchFailedWithReason));
    public static string Status_HpFormat => GetString(nameof(Status_HpFormat));
    public static string Status_PositionFormat => GetString(nameof(Status_PositionFormat));
    public static string Status_MapFormat => GetString(nameof(Status_MapFormat));

    public static string Format(string name, params object[] args) =>
        string.Format(CultureInfo.CurrentCulture, GetString(name), args);

    private static string GetString(string name) =>
        ResourceManager.GetString(name, _resourceCulture) ?? name;
}
